spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Daniel11V/ecommerce-backend-java-config-properties.git
server:
  port: 8888